arbiter5:
  build: ./
  volumes:
    - ./log:/root/arbiter/log
    - ./mocks:/root/arbiter/mocks
  environment:
    PROFIT: 5

arbiter10:
  build: ./
  volumes:
    - ./log:/root/arbiter/log
    - ./mocks:/root/arbiter/mocks
  depends_on:
      - "arbiter5"
    command: "sleep 10"
  environment:
    PROFIT: 10

arbiter20:
  build: ./
  volumes:
    - ./log:/root/arbiter/log
    - ./mocks:/root/arbiter/mocks
  depends_on:
      - "arbiter10"
    command: "sleep 10"
  environment:
    PROFIT: 20