arbiter5:
  build: ./
  volumes:
    - ./log:/root/arbiter/log
    - ./mocks:/root/arbiter/mocks
  environment:
    PROFIT: 5

arbiter10:
  build: ./
  volumes:
    - ./log:/root/arbiter/log
    - ./mocks:/root/arbiter/mocks
  environment:
    PROFIT: 10

arbiter20:
  build: ./
  volumes:
    - ./log:/root/arbiter/log
    - ./mocks:/root/arbiter/mocks
  environment:
    PROFIT: 20